### ISSUE TITLE
ValueError exception thrown

### ISSUE THREAD

**Issue by alenmeister** [sgratzl/slack-cleaner#1]
Hey there!

Been looking for a python program to bulk delete messages from Slack, and stumbled upon this project. Anyway, I pulled the image from Docker and ran slack-cleaner with the following arguments:
`/backup # slack-cleaner --token TOKEN --message --channel test --user "*"`

This got thrown back at me:
```
Running slack-cleaner v0.4.0
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 11, in <module>
    load_entry_point('slack-cleaner==0.4.0', 'console_scripts', 'slack-cleaner')()
  File "/usr/local/lib/python2.7/site-packages/slack_cleaner/cli.py", line 380, in main
    message_cleaner()
  File "/usr/local/lib/python2.7/site-packages/slack_cleaner/cli.py", line 350, in message_cleaner
    _channels = resolve_channels()
  File "/usr/local/lib/python2.7/site-packages/slack_cleaner/cli.py", line 317, in resolve_channels
    _channels.extend([(id, name, 'channel') for (id, name) in get_channel_ids_by_pattern(args.channel_name, not args.regex)])
ValueError: too many values to unpack
```

Any ideas?

**Comment by sgratzl** [comment]
wait till docker hub built the latest image and then try again.

**Comment by jaketoolson** [comment]
I get this same error using PIP to install.

**Comment by sgratzl** [comment]
> I get this same error using PIP to install.

the pip version isn't maintained by myself but by the original author. If you want this version you have to install it via `pip install -e git+https://github.com/sgratzl/slack-cleaner.git@master#egg=slack_cleaner`
