### ISSUE TITLE
Unable to use botname and pattern argument

### ISSUE THREAD

**Issue by grappler** [sgratzl/slack-cleaner#10]
I only wanted to delete messages from one incoming webhook in a channel but the `botname` did not want to filter out those messages. I tired a few different variation but I always got 0 messages back.

I tried to filter the messages by the title or message but that did not seem to work too. I would like to delete the messages from "production Monolog" but keep those from "staging-server"

![image](https://user-images.githubusercontent.com/1785641/34512774-3457d944-f086-11e7-9820-02971f14acae.png)

**Comment by sgratzl** [comment]
take a look at the develop branch using the contained python module you have a fine granular access to the messages and whether to delete them or not
