### ISSUE TITLE
missing_argument error when trying to use provided example

### ISSUE THREAD

**Issue by Litwilly** [sgratzl/slack-cleaner#101]
Not sure if this is still a working utility, getting missing_argument error for the following execution:

`
slack-cleaner --token $TOKEN --message --channel general --user "*"
`

![image](https://user-images.githubusercontent.com/7134135/131155446-d0617edf-7825-456e-b20f-ecf9c065a0e5.png)

- Version: v0.7.4
- Python Version: 3.8

**Additional context**
I've also tried to use slack-cleaner2 and get a similar error but with just a bit more text

![image](https://user-images.githubusercontent.com/7134135/131155816-1f2ef5c1-37bc-4429-90c4-e5b0916c93a8.png)

This is the scopes my current application has installed into the workspace: 

![image](https://user-images.githubusercontent.com/7134135/131155898-e804ee8c-d4b7-4845-808d-1cf395e41bc4.png)

**Comment by sgratzl** [comment]
according to the docs that happens when you have an organization wide token, see https://api.slack.com/methods/conversations.list#arg_team_id

**Comment by sgratzl** [comment]
add support for `team_id` in https://github.com/sgratzl/slack_cleaner2/releases/tag/v3.0.7

**Comment by Litwilly** [comment]
so for slack-cleaner-2 to use a team_id would it look like this:

`s = SlackCleaner('xoxp-token', 'team-id')`

**Comment by Litwilly** [comment]
nevermind got it 

`s = SlackCleaner('xoxp-token', team_id='team-id')`
