### ISSUE TITLE
how 'catch' "unknown error occurred" ?

### ISSUE THREAD

**Issue by jpwynn** [sgratzl/slack-cleaner#103]
in my code I use 

        try:
          msg.delete(replies=True, files=True)
          time.sleep(.5)
        except Exception as e:
           <code to print "F" to console as I look thru conversations>

But when an "unknown error" occurs it;s not throwing an exception I can catch, it's printing a message, so I get a LOT of these messages:

```
conversations.replies: unknown error occurred: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.replies) The server responded with: {'ok': False, 'error': 'thread_not_found'}
```
It seems like rather than print a message it ought to throw an exception that can be caught and handled?

**Comment by jpwynn** [comment]
oops wrong version of slack cleaner I'm using 2

**Comment by sgratzl** [comment]
take a look at the return value of `delete`. https://github.com/sgratzl/slack_cleaner2/blob/main/slack_cleaner2/model.py#L437

yes it is designed to keep working on errors but it returns the error if it encounters one.
