### ISSUE TITLE
Mac M1 Support

### ISSUE THREAD

**Issue by amandiobm** [sgratzl/slack-cleaner#104]
Hey all, 

how hard it would be to add support to Mac M1?

Best regards

**Comment by sgratzl** [comment]
this is a pure python library, I don't understand why Mac M1 shouldn't be supported with the right python version

**Comment by amandiobm** [comment]
Is just the docker image provided. 

```WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested```

**Comment by sgratzl** [comment]
easiest to use the python package instead
