### ISSUE TITLE
How to delete channels?

### ISSUE THREAD

**Issue by castroteam** [sgratzl/slack-cleaner#106]
All the examples are deleting messages in a channel, but is there a way to delete the channel itself? Thanks

**Comment by sgratzl** [comment]
this tools is not designed to delete a whole channel. Moreover, there is a better version of the slack cleaner located at https://github.com/sgratzl/slack_cleaner2. However also there it is not designed for deleting channels. 

I would take a look at the direct Slack API (https://slack.dev/python-slack-sdk/)
