### ISSUE TITLE
429 Too many requests

### ISSUE THREAD

**Issue by 4oby** [sgratzl/slack-cleaner#13]
Started cleaning slack recently from CI bot spam
Once I got over 100 messages I start receiving:
 `Failed to delete (429 Client Error: Too Many Requests for url: https://slack.com/api/chat.delete?token=<my token>`

According to [Slak's Documentation](https://api.slack.com/docs/rate-limits) the error shows up once you reach the limit and you should start parsing `Retry-After` parameter in the response.

**Comment by sgratzl** [comment]
you can try to use the `--rate 1` to limit the rate of requests to one per second

**Comment by 4oby** [comment]
This actually works!
Thanks!
