### ISSUE TITLE
Cleaner does not delete all messages in channel

### ISSUE THREAD

**Issue by desmax** [sgratzl/slack-cleaner#14]
Im sure that there are more messages in channel but it only deletes messages that are available in Slack itself. what can be done?

**Comment by sgratzl** [comment]
you mean the 10k border?

**Comment by desmax** [comment]
@sgratzl yes, I expected that if I delete some messages than I will be able to delete\see messages that were hidden behind 10k border.

**Comment by sgratzl** [comment]
I don't think that you can get them via REST api either.
