### ISSUE TITLE
--botname doesn't seem to delete messages [weird output of # of messages to be deleted]

### ISSUE THREAD

**Issue by ikjadoon** [sgratzl/slack-cleaner#16]
Hello! I'm running slack-cleaner v.0.4.0 on Python 3.6, via PowerShell. I'm trying to delete one particular bot's messages from one particular channel:

``PS C:\1\insta_env> slack-cleaner --token xxxx --message --channel internal-updates --botname notion``
``Running slack-cleaner v0.4.0``
``Deleting messages from channel internal-updates``

``[92m0[0m message(s) will be cleaned.``

``Now you can re-run this program with `--perform` to actually perform the task.``

I guess it's a character issue, but still, even after initiating the delete via --perform with this output,

``[92m0[0m message(s) cleaned.``

All the messages remain. None are deleted. Have I missed a crucial step here? This is the bot whom I'm trying to wipe.

Here's what the app looks like:

![2018-04-05_15-47-32](https://user-images.githubusercontent.com/3848795/38388309-df36760e-38e8-11e8-96f0-5a49d99d3e10.png)

![2018-04-05_15-48-30](https://user-images.githubusercontent.com/3848795/38388312-e18d5d8c-38e8-11e8-8853-9461407cb080.png)

**Comment by sgratzl** [comment]
re ansi escape codes in powershell -> #17

**Comment by sgratzl** [comment]
there is a new option `--info` to get a list of all users and so on. Please, check if you have the right name.

**Comment by sgratzl** [comment]
maybe related to #36 such that not `--botname` implies `--bot`

**Comment by sgratzl** [comment]
@ikjadoon any updates on this issue from your side?

**Comment by sgratzl** [comment]
stale
