### ISSUE TITLE
Delete all direct messages older than a given date?

### ISSUE THREAD

**Issue by gmask** [sgratzl/slack-cleaner#22]
Around 90% of our Slack space is comprised of direct messages, and we're fast approaching the 10k nag. Can I delete DMs using wildcards?

I've tried:
```
slack-cleaner --rate $RATE --token $TOKEN --message --direct "*" --user "*" --before $DATED $1
```
With no luck.

**Comment by sgratzl** [comment]
No you cannot. Even with all rights I was only able so far to delete my own direct messages that I wrote. (using `--regex` and `--direct=".*"`). seems to be an API limitation. You can test it by just going to any direct message in your slack client directly and try to delete a message from your opponent partner. You cannot. :(
