### ISSUE TITLE
How to delete conversations from usernames with spaces?

### ISSUE THREAD

**Issue by HouseBaratheon** [sgratzl/slack-cleaner#31]

**Comment by sgratzl** [comment]
Hi,
the easiest solution would be to use the `develop` branch of this repository. It contains a rewrite of the slack_cleaner focusing on a python module like implementation. 

Thus you can easily have access to relevant user information and filter according to that. 

corresponding user model: 
https://github.com/sgratzl/slack-cleaner/blob/823b0b5630b8a0915f9494d2c448d22f0089e3a0/slack_cleaner2/model.py#L7-L57

usage see README

**Comment by sgratzl** [comment]
@HouseBaratheon had you a chance to try out the develop version to solve your issue?

**Comment by HouseBaratheon** [comment]
@sgratzl I did not, no, but I did realize how dumb my question was lol. The need that originally inspired my ask is no longer a worry, but if it ever crops up again, I'll be sure to tackle.
