### ISSUE TITLE
Can not delete from private channel 

### ISSUE THREAD

**Issue by 4mig4** [sgratzl/slack-cleaner#32]
I am using --group and the name of the channel is correct as far as I can tell.

Are there some new Slack limitation on the channel containing more than X messages then can't delete with the API ? 

```
Running slack-cleaner v0.3.0
Channel, direct message or private group not found
```

**Comment by sgratzl** [comment]
> Running slack-cleaner v0.3.0

this is the original version which is not supported by this repo. Please use the latest version `0.4.1` which includes an `--info` command

**Comment by 4mig4** [comment]
ok , this seems to be some new restrictions having been put in place by Slack.

**Comment by 4mig4** [comment]
Also your repo does not list tags fro versions. Please tag your releases
