### ISSUE TITLE
Backup feature

### ISSUE THREAD

**Issue by macpijan** [sgratzl/slack-cleaner#33]
Hi.
I used this one for cleaning up my space from files and it works great, thanks!  :1st_place_medal: 
I used it with a: https://github.com/auino/slack-downloader which is a simple script to download the files, but gets the job done as well.
I'm wondering if you think it would be desired to add a backup feature to this user-friendly toolkit of yours.

**Comment by sgratzl** [comment]
with https://github.com/sgratzl/slack-cleaner/blob/develop/example/archive.py I added a simple example, how to use the new module version of this package to archive messages in a MongoDB

**Comment by sgratzl** [comment]
in combination with the new `download` method of a SlackFile (see https://slack-cleaner2.readthedocs.io/en/latest/modules.html#slack_cleaner2.model.SlackFile.download) also files can be easily archived

**Comment by sgratzl** [comment]
closing in favor of the develop / slack_cleaner2
