### ISSUE TITLE
Failed to delete (cant_delete_message)->

### ISSUE THREAD

**Issue by KuNman** [sgratzl/slack-cleaner#37]
Hello.
I can't delete any message from logs channel.
I run : `slack-cleaner --token TOKEN --message --channel CHANNEL --bot --perform --rate 5`.
Scopes under this token : 
>users:read
> channels:history
> channels:read 
>chat:write:user
>chat:write:bot

**Comment by sgratzl** [comment]
does it return the `cannot delete message` error message or are just no messages are about to be deleted. In the latter case, could be a duplicate to #38

**Comment by botzill** [comment]
Having the same issues. I have a channel with lot's of messages from an app bot I have. When I di 


```
slack-cleaner --token ${TOKEN} --message --channel ${CHANNEL} --bot --perform --rate 2
```

I get `Failed to delete (cant_delete_message)->`. Any idea how to solve this and way I get this?

I can delete users messages ok, but issues are with bot ones. 

Thx.

**Comment by sgratzl** [comment]
Hi can you try the develop branch of this project. it follows a different approach, a pure python one. but allows you more control about which messages should be deleted. 

https://github.com/sgratzl/slack-cleaner/tree/develop and https://slack-cleaner2.readthedocs.io/en/latest/modules.html

thus it would be easier to come up with a more specific reason why the message cannot be deleted

**Comment by botzill** [comment]
I did and I get 

```
Traceback (most recent call last):
  File "/Users/mac/.virtualenvs/crawless/bin/slack-cleaner", line 10, in <module>
    sys.exit(main())
  File "/Users/mac/.virtualenvs/crawless/lib/python3.7/site-packages/slack_cleaner2/cli.py", line 216, in main
    _delete_messages(slack, args)
  File "/Users/mac/.virtualenvs/crawless/lib/python3.7/site-packages/slack_cleaner2/cli.py", line 73, in _delete_messages
    user = _resolve_user(slack, args)
  File "/Users/mac/.virtualenvs/crawless/lib/python3.7/site-packages/slack_cleaner2/cli.py", line 42, in _resolve_user
    return next(filter(match_user(args.user), slack.users))
  File "/Users/mac/.virtualenvs/crawless/lib/python3.7/site-packages/slack_cleaner2/predicates.py", line 166, in match_user
    regex = re.compile('^' + pattern + '$', re.I)
TypeError: can only concatenate str (not "NoneType") to str
```

When running:

```
slack-cleaner --token ${TOKEN} --message --channel ${CHANNEL} --bot --perform --rate 2
```

**Comment by botzill** [comment]
Hi @sgratzl, any update on this issue?

**Comment by sgratzl** [comment]
the easiest way would be to write a custom python script and use the library directly. 

e.g. untested python code but should be quite right

```python
from slack_cleaner2 import *

s = SlackCleaner(TOKEN, sleep_for=2)
channel = next(c for c in s.channels if c.name == CHANNEL, None)
if channel:
  for msg in channel.msgs():
    if msg.bot:
      msg.delete()

```

**Comment by sgratzl** [comment]
re cli: you can try to add ` --user "*"`

**Comment by botzill** [comment]
@sgratzl still getting the same issues with `cant_delete_message` with the code you're mentioning.

How can we know that is the issues? I'm using a legacy token.

**Comment by sgratzl** [comment]
when looking at https://api.slack.com/methods/chat.delete there are the following restrictions:

```
When used with a typical user token, may only delete messages posted by that user.

When used with an admin user's user token, may delete most messages posted in a workspace.

When used with a bot user's token, may delete only messages posted by that bot user.
```

so are you an admin? Moreover, you can try to set the `as_user` flag as in 

```python
msg.delete(as_user=True)
```

**Comment by botzill** [comment]
Hi.

Sorry, I was not admin, with admin token I can delete now. 

Thx!

**Comment by sgratzl** [comment]
happy that you found the issue

**Comment by cinguva** [comment]
> the easiest way would be to write a custom python script and use the library directly.
> 
> e.g. untested python code but should be quite right
> 
> ```python
> from slack_cleaner2 import *
> 
> s = SlackCleaner(TOKEN, sleep_for=2)
> channel = next(c for c in s.channels if c.name == CHANNEL, None)
> if channel:
>   for msg in channel.msgs():
>     if msg.bot:
>       msg.delete()
> ```

little syntax change, channel = next((c for c in s.channels if c.name == 'random'), None)
missing paranthesis

**Comment by sgratzl** [comment]
thx
