### ISSUE TITLE
add `verify` option to turn off SSL check

### ISSUE THREAD

**Issue by sorvis** [sgratzl/slack-cleaner#41]
Hello,

Thank you very much for making this fork of slack-cleaner and maintaining it. 

I'm trying to run slack-cleaner behind my company proxy which messes up SSL certificates to make them not valid. Is it possible to disable the SSL check as a flag or something?

> Failed to delete (HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.delete?token= (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),)))->

**Comment by sgratzl** [comment]
@sorvis First things first. I edited your issue. Please never ever post any Slack Token. However, it is part of the history. Thus please invalidate the token you used.

see also http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

-> `session.verify = False` or `session.verify = 'path/to/certfile'`

**Comment by sorvis** [comment]
@sgratzl thank you very much for catching my carelessness on the token. I have re-issued it as you suggested.
