### ISSUE TITLE
Handle gracefully 429 HTTP error

### ISSUE THREAD

**Issue by eschizoid** [sgratzl/slack-cleaner#44]
Rather than having the user guess what the `rate` should be, it would be ideal if the application handles gracefully 429's errors ` Client Error: Too Many Requests`.

**Comment by eschizoid** [comment]
> -> seems like the are returning a Retry-After header indicating how long to wait before continuing

Correct, and my suggestion is that the library should handle this and do not expect the user to figure out how long to wait.

From the link you sent:

```
By programmatically evaluating the Retry-After header you can wait for the indicated number of seconds before retrying the same request or continuing to use that method for this workspace.
```

**Comment by sgratzl** [comment]
seems like that the slacker library already supporting it: 

https://github.com/os/slacker/blob/71558d362fc40f2525c63ae4a472b345db2a5d5d/slacker/__init__.py#L70-L86

and that this project already set the retry count to 2

https://github.com/sgratzl/slack-cleaner/blob/d89e8294f9c8fe7d1e31f65e28b77b4f98050ba4/slack_cleaner/cli.py#L36-L37

no idea what else to do?

**Comment by eschizoid** [comment]
@sgratzlI think making `rate_limit_retries` available as command argument would be ideal (if not provided, default to the original value). I can take a take and stab and PR if you are on board with the idea.

**Comment by sgratzl** [comment]
sounds good, thx

**Comment by jgengo** [comment]
I think the rate-limit should be handled by the higher-level interface Slacker and not by the client of the interface.

**Comment by puzzlement** [comment]
The code at https://github.com/sgratzl/slack-cleaner/issues/44#issuecomment-464484880 is buggy, although I'm not sure if it was at the time you posted that comment.

The Slacker library passes its rate_limit_retries down into a huge number of helper objects in its init function: https://github.com/os/slacker/blob/master/slacker/__init__.py#L1186, and slack-cleaner setting `rate_limit_retries` on the `slack` object itself after its init function has already run means that those helper objects all have `rate_limit_retries` set to 0.

**Comment by puzzlement** [comment]
https://github.com/sgratzl/slack-cleaner/pull/71 to simply pass it to the Slacker object. You could do some kind of iteration over slack.api, slack.im, and all the other helper objects, but at that point you're highly dependant on the internals of the Slacker class (as the code at https://github.com/sgratzl/slack-cleaner/issues/44#issuecomment-464484880 already was).
