### ISSUE TITLE
Channel, direct message or private group not found

### ISSUE THREAD

**Issue by aeonagency** [sgratzl/slack-cleaner#47]
Using --channel works, however, whenever I try to run the command with --group to delete all messages from a private channel it does not recognize the channel.

**Comment by sgratzl** [comment]
can you try running with `--info` command to list all known channels, groups, ...

**Comment by aeonagency** [comment]
I did, however, private channels comes out empty even though I have private channels.

**Comment by sgratzl** [comment]
are you a member of those private channels aka groups? as far as I know one can only list channels one is member of

**Comment by aeonagency** [comment]
Yes, I am. Otherwise I wouldn't be seeing them on Slack either.

**Comment by tiholic** [comment]
I too face the same problem on different slack workspaces. I have full control of both the workspaces.

Public and few private channels are listed with `--info` but private channels which were initially created as public and made private later are not listed.

**Comment by sgratzl** [comment]
can you try the following REST api call, just replace the `TOKEN` with your token.
```
https://slack.com/api/conversations.list?types=public_channel%2Cprivate_channel%2Cmpim%2Cim&pretty=1&token=TOKEN
```

it should list all channels,... that are accessible.

**Comment by tiholic** [comment]
@sgratzl simple get call works

![image](https://user-images.githubusercontent.com/14252381/57249650-20732100-7063-11e9-8ca7-21073e563d5a.png)

**Comment by sgratzl** [comment]
thx for checking. I could reproduce the error, in the test slack instance: https://slack-cleaner.slack.com

```
>>> s = SlackCleaner(token)
>>> print(s.conversations)
[general, public2private, random, slackbot, samuel_gratzl]
```
after making `public2private` private:
```
>>> s = SlackCleaner(token)
>>> print(s.conversations)
[general, random, slackbot, samuel_gratzl]
```
