### ISSUE TITLE
Getting cant_delete_message for direct messages

### ISSUE THREAD

**Issue by davidseek** [sgratzl/slack-cleaner#48]
I'm the owner of the Slack workspace
and I'm trying to remove messages from Direct Messages.

It deleted my own messages without any issues.
But the other person's messages I can't delete.
Not a single one.

Getting (with --rate of 3) on every message:

```
Failed to delete (cant_delete_message)->
{   u'client_msg_id': u'XXX',
    u'text': u'XXX ',
    u'ts': u'XXX',
    u'type': u'message',
    u'user': u'XXX'
}
```

Any ideas?

**Comment by sgratzl** [comment]
Hi,
that is a security restriction of Slack itself. You can only delete your own direct messages even with administrator rights.

**Comment by davidseek** [comment]
Yeah okay. 
Well quiet miss-leading then tho.
Should be clearly stated in documentations.

But got it.
