### ISSUE TITLE
Fedora packages

### ISSUE THREAD

**Issue by rapgro** [sgratzl/slack-cleaner#51]
Hi,
let me kindly announce official packages available in the Fedora repository, currently for Rawhide, F30 and EPEL7 (latter as addon for RHEL7/CentOS7). I'm the proud maintainer of both packages named slack-cleaner and python-slacker (as dependency).
Commands to install:
```
# Fedora
dnf install slack-cleaner
# EPEL7
yum install -y epel-release ; yum install slack-cleaner
```

Regards.

**Comment by sgratzl** [comment]
cool thx, would be create if you create a PR that includes this information in the README
