### ISSUE TITLE
Deleting Threads (conversations.replies)

### ISSUE THREAD

**Issue by deftm0nk** [sgratzl/slack-cleaner#53]
Everything works really well, except that when deleting all messages on a channel, I find that the replies on a thread are usually left behind. I've tried most of the args to try getting rid of it but am hitting a wall.

**Comment by sgratzl** [comment]
can you give the develop version a try? the python API there gives you access to all replies of a message, see also https://slack-cleaner2.readthedocs.io/en/latest/modules.html#slack_cleaner2.model.SlackMessage.replies

untested pseudo code:

```python
from slack_cleaner2 import *

s = SlackCleaner('SECRET_TOKEN', sleep_for=1)

# delete every message
for msg in s.msgs(s.conversations):
  for reply in msg.replies():
    reply.delete()
  msg.delete()
```

**Comment by deftm0nk** [comment]
Sorry mate. I'm having issues getting it to run.

I did a clean install after having some clashes, and I'm stuck here while trying to test out in notebook first

from slack_cleaner2 import *

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-e70daaafb7c7> in <module>()
----> 1 from slack_cleaner2 import *

/home/xxx/src/slack-cleaner/slack_cleaner2/__init__.py in <module>()
      5 from .predicates import and_, or_, is_not_pinned, is_bot, match, is_name, match_text, match_user, is_member, by_user, \
      6   by_users
----> 7 from .slack_cleaner2 import SlackCleaner
      8 from .util import a_while_ago
      9 

/home/xxx/src/slack-cleaner/slack_cleaner2/slack_cleaner2.py in <module>()
      4 """
      5 from requests.sessions import Session
----> 6 from slacker import Slacker
      7 
      8 from .logger import SlackLogger

ModuleNotFoundError: No module named 'slacker'

**Comment by sgratzl** [comment]
strange, `slacker` is defined as an requirement in the [`setup.py`](https://github.com/sgratzl/slack-cleaner/blob/develop/setup.py)

I just placed around with the try out version of jupyther, 
1. opened a terminal and executed; `pip install slack_cleaner2`
1. in a notebook executed:

```python
from slack_cleaner2 import *
s = SlackCleaner('TOKEN', sleep_for=1)
list(s.msgs())
```

listed all my messages

**Comment by kpkirsch** [comment]
Anyway to clean up threads left behind? this was my original input
`slack-cleaner --token <tokem> --message --channel <channel> --user "*" --keeppinned --as_user --perform`

**Comment by jgengo** [comment]
I've opened a pull request for that :
https://github.com/sgratzl/slack-cleaner/pull/55

**Comment by sgratzl** [comment]
> 
> 
> I've opened a pull request for that :
> #55

thx @jgengo
