### ISSUE TITLE
Failed to delete

### ISSUE THREAD

**Issue by aronday** [sgratzl/slack-cleaner#54]
Im getting an error when trying to delete 

`Running slack-cleaner v0.6.0
Deleting messages from channel ideas
Failed to delete (missing_scope)->
{   u'subtype': u'channel_join',
    u'text': u'<@ULC5K5DKR> has joined the channel',
    u'ts': u'1562772926.000200',
    u'type': u'message',
    u'user': u'ULC5K5DKR'}`

**Comment by aronday** [comment]
Issue was down to wrong scopes on API. Fixed

**Comment by krazyjakee** [comment]
@aronday i have set up scopes according to the readme but still have this issue. What am i missing?

**Comment by sgratzl** [comment]
cannot you delete any messages or just a certain subset?

**Comment by leabdalla** [comment]
Same problem here.
I'm trying to clean a public channel and getting failed for all messages:

    Failed to delete (missing_scope)->
    {   u'subtype': u'channel_join',
        u'text': u'<@xxxx> has joined the channel',
        u'ts': u'xxxx.000200',
        u'type': u'message',
        u'user': u'xxxxx'}

I'm currently using these scopes on token:

Bot Token Scopes
- channels:history
- channels:manage
- channels:read
- chat:write
- groups:history
- groups:read
- usergroups:write
- users:read

User Token Scopes
- channels:history
- channels:read
- channels:write
- groups:history
- groups:read
- groups:write
- users:read

Any help?
