### ISSUE TITLE
Messages not found

### ISSUE THREAD

**Issue by krazyjakee** [sgratzl/slack-cleaner#56]
![image](https://user-images.githubusercontent.com/623463/63497433-05b6a200-c4c4-11e9-9e45-3b99c030abeb.png)

After deleting files, these messages appear in the channel history. These messages cannot be found by slack-cleaner to delete.

**Comment by jgengo** [comment]
Hello @krazyjakee 

I also tried to get the same error you got by deleting first files and then deleting messages
```
slack-cleaner --token $token --rate 1 --file --channel test --user='*' --perform
slack-cleaner --token $token --rate 1 --message --channel test --user='*' --perform
```

But I didn't get any error.
Could you please be more specific, tell us what you tried exactly, in the same order?

**Comment by sgratzl** [comment]
> After deleting files, these messages appear in the channel history. These messages cannot be found by slack-cleaner to delete.

as far as I understood, slack has changed the file logic as just being attachments to messages. Thus, what you see are the remainder of the file. You have to delete the messages, too then it should be gone. 

Note: Those tombstone messages also appear when one deletes a message which is the start of a thread. v0.7.1 should handles them properly and deletes also all the thread messages
