### ISSUE TITLE
Webhook message delete not possible

### ISSUE THREAD

**Issue by StefanSa** [sgratzl/slack-cleaner#60]
Hi,
i can delete normal message, but no webhook message.
i always get the error message:
`slack-cleaner --token <TOKEN> --message --channel alerts --user "*"`
`0 message(s) cleaned.`

**Comment by sgratzl** [comment]
do you know how I can reproduce it? I have a slack-cleaner slack workspace for testing purposes

**Comment by StefanSa** [comment]
Hi Samuel,
zuerst einmal Grüße nach Österreich.
Hast du die Chance per Webhook an Slack ein Nachricht zu versenden ?

Hi Samuel,
first greetings to Austria.
Do you have the chance to send a message to Slack via webhook?

Gruß / regards
Stefan

**Comment by sgratzl** [comment]
I just checked. 

have you tried
```bash
slack-cleaner --token <TOKEN> --message --channel alerts --bot
```

bots / apps aren't regular users

**Comment by sgratzl** [comment]
btw. with the latest https://github.com/sgratzl/slack_cleaner2 version it would be
```python
from slack_cleaner2 import SlackCleaner2
s = SlackCleaner2(TOKEN)
for msg in s.c.alerts.msgs():
  msg.delete()
```

**Comment by StefanSa** [comment]
Sumuel,
`--bot` was the trick, all webhook messages are deleted.
i close the ticket now, thanks for your help.
