### ISSUE TITLE
Human readable 'before' or 'after' parameters

### ISSUE THREAD

**Issue by VuokkoVuorinnen** [sgratzl/slack-cleaner#61]
**Is your feature request related to a problem? Please describe.**
I want to run your script on a cron, so I would like to issue the same command every day. For example:

slack-cleaner --channel debug --bot --perform --before 'yesterday'

To remove all messages older than a day. Right now I have to calculate the date it was yesterday using some other library or tool.

**Describe the solution you'd like**
I would like the --before and the --after parameters to take human readable input as well as YYYYMMDD

**Describe alternatives you've considered**
Wrapping your tool in ruby, since it's pretty easy to work with dates in Ruby

**Additional context**
I'm a lazy sysadmin and would 100% understand that you can't/won't implement this feature. Btw: amazing product, please keep it alive!

**Comment by sgratzl** [comment]
thx for the suggestion, I will take a look at it. You might also wanna give the improved version a try https://github.com/sgratzl/slack_cleaner2 which has a nice `a_while_ago` function. For the current version I tend to use the bash date function like `$(date -d "-1 day")` in your case to compute the right day

**Comment by sgratzl** [comment]
wontifx, in favor of slack-cleaner2
