### ISSUE TITLE
Add option to delete from all channels, ims, mims, etc

### ISSUE THREAD

**Issue by vdurante** [sgratzl/slack-cleaner#65]
I like to cleanup my whole slack every now and them. Listing every single options and iterating through them is a pain. Would be great to have an option to run `slack-cleaner [...] --all-channels` (the same for ims, etc) and cleanup everything at once.

**Comment by sgratzl** [comment]
you could give https://github.com/slack_cleaner2 a try. in the end it will reduce to:

```python
s = SlackCleaner(...)
for msg in s.msgs():
  msg.delete()

```

**Comment by sgratzl** [comment]
alternative is can use the regex versions which will allow wildcards (like .*)

**Comment by vdurante** [comment]
Such a fast response. Thank you so much. Just to make sure, if I query `s.msgs()` it includes absolutely every single message (directs, groups, channels, mpdirect)?


Therefore, the code bellow would pretty much erase 2018 from my slack?
```
after = "20180101"
before = "20181231"
for msg in s.msgs(after=after, before=before):
        msg.delete()

for f in s.files(after=after, before=before):
        f.delete()
```

**Comment by sgratzl** [comment]
hm ... I think it won't catch replies by now:

```python
after = "20180101"
before = "20181231"
for msg in s.msgs(after=after, before=before):
        for reply in msg.replies():
             reply.delete()
        msg.delete()

for f in s.files(after=after, before=before):
        f.delete()
```

Moreover, the standard Slack restrictions will apply such that you can only delete the IMs that you wrote but not the one of your partner. Same you cannot delete ims of other users. 

so an alternative that should produce less errors (untested) but just replace the `.delete` with some logging to confirm your targeted behavior

````python
s = SlackCleaner(TOKEN, sleep_for=1)
for channel in (s.channels + s.groups + s.mpim):
  with s.log.group(channel.name):
     for msg in channel.msgs(after=after, before=before):
        for reply in msg.replies():
           reply.delete()
        msg.delete()

for channel in s.ims:
  with s.log.group(channel.name):
     for msg in channel.msgs(after=after, before=before):
        for reply in msg.replies():
           if reply.user == s.myself:
              reply.delete()
        if msg.user === s.myself:
           msg.delete()
s.log.summary()
````
