### ISSUE TITLE
How I can delete messages from webhooks?

### ISSUE THREAD

**Issue by juanantoniodamianv** [sgratzl/slack-cleaner#66]
I trying to delete all my messages from a incoming webhooks private channel, but I got "Failed to delete (cant_delete_message)"

`slack-cleaner --token "" --message --group "xxxx" --user "*" --bot --perform`

**Comment by keishidev** [comment]
This is permission problem , you might be add permission on the below.

Deleting messages from private channels
 groups:history
 groups:read
 chat:write:user
 users:read
 Deleting messages 

API Document
https://api.slack.com/methods/chat.delete

cant_delete_message | Authenticated user does not have permission to delete this message.

**Comment by juanantoniodamianv** [comment]
Solved, thank you @keishidev
