### ISSUE TITLE
Users with spaces in their usernames.

### ISSUE THREAD

**Issue by ceblack** [sgratzl/slack-cleaner#7]
It appears that there isn't a way to delete direct messages where one or more of the users has a username with a space in it. One of my users has a "First Last" username. I've tried putting the name in quotes, as well as using the "@" code (ex: <@U2B7M4JKQ>). This @ code I tried with and without the opening and closing brackets, as well as with quotations.

**Comment by sgratzl** [comment]
can you send me the command line you are executing with the username replace with dummy values but having the same pattern?

**Comment by sgratzl** [comment]
are you sure regarding the user name. I checked my slack members and while the list of members shows that some use their full name as user name. They internally have the name part of their email address. You can modify `cli.py` such that it will print the list of users to confirm the user names.

**Comment by sgratzl** [comment]
can you try to find out whether you have the right name by listing all of them using the new `--info` feature= #18

**Comment by sgratzl** [comment]
so when you execute the program with `--info` to list all users, the desired user name does not work?

as an alternative you can check out the new develop branch which uses a scripted approach instead of a command line one.

**Comment by hindfelt** [comment]
when I run with the --info parameter 
(slack-cleaner --token <xoxp-3550220201-and-so-on> --mpdirect Mary,Tom Joson,Mpetbe --info) 

it returns slack-cleaner: error: unrecognized arguments: Jonson,Mpetbe

**Comment by sgratzl** [comment]
try something like `slack-cleaner --token <yourtoken> --info`

**Comment by hindfelt** [comment]
Then I get this error message..

Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 9, in <module>
    load_entry_point('slack-cleaner2==0.1.0', 'console_scripts', 'slack-cleaner')()
  File "/Library/Python/2.7/site-packages/slack_cleaner2-0.1.0-py2.7.egg/slack_cleaner2/cli.py", line 209, in main
    _show_infos(slack)
  File "/Library/Python/2.7/site-packages/slack_cleaner2-0.1.0-py2.7.egg/slack_cleaner2/cli.py", line 23, in _show_infos
    _print_dict('users', {u.id: '{} = {}'.format(u.name, u.real_name) for u in slack.users})
  File "/Library/Python/2.7/site-packages/slack_cleaner2-0.1.0-py2.7.egg/slack_cleaner2/cli.py", line 23, in <dictcomp>
    _print_dict('users', {u.id: '{} = {}'.format(u.name, u.real_name) for u in slack.users})
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128
