### ISSUE TITLE
Fail to delete(invalid_arguments)

### ISSUE THREAD

**Issue by narongwate-scm** [sgratzl/slack-cleaner#70]
I got an error message "Fail to delete(invalid_arguments)" when using --perform option, But when not use --perform it looks like work.

What did I do wrong?

command:
slacker-cleaner --token xxxx --message --group groupName --bot --perform 

 - Device: Macbook Pro
 - OS: MacOS 10.15.3
 - Version 0.6.3

I have the same problem when I install it from pip and "docker container".

**Comment by lucbas** [comment]
I am facing the same problem on my Mac using Docker.

I have directly hooked into the bash and run the following command:

`slacker-cleaner --token xxxx --message --group groupName --bot --perform
`
The previous command successfully lists all messages to delete:
`slacker-cleaner --token xxxx --message --group groupName --bot `

Maybe it has something to do with bot messages?

I double-checked the scopes, and they correspond to the doc.

**Comment by sgratzl** [comment]
please be aware of the rate limits when deleting messages, see also 

https://github.com/sgratzl/slack-cleaner#tips

e.g. add `--rate 1`

is it a specific bot message or all of them ?

**Comment by mqdeandrade** [comment]
@sgratzl I am having the same issue. It seems to be all the messages from the laravel log bot https://laravel.com/docs/5.8/logging
As it is an API error log there are stack traces embedded in each message so perhaps there is an escaping issue? Here is a (hopefully well redacted) example
`{   'attachments': [   {   'color': 'a30200',
                           'fallback': 'Expected response code 354 but got '
                                       'code "550", with message "550 5.7.0 '
                                       'Requested action not taken: too many '
                                       'emails per second\n'
                                       '"',
                           'fields': [   {   'short': False,
                                             'title': 'Level',
                                             'value': 'ERROR'},
                                         {   'short': False,
                                             'title': 'Exception',
                                             'value': '```{\n'
                                                      '    "class": '
                                                      '"Swift_TransportException",\n'
                                                      '    "message": '
                                                      '"Expected response code '
                                                      '354 but got code '
                                                      '\\"550\\", with message '
                                                      '\\"550 5.7.0 Requested '
                                                      'action not taken: too '
                                                      'many emails per '
                                                      'second\\r\\n\\"",\n'
                                                      '    "code": 550,\n'
                                                      '    "file": '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457",\n'
                                                      '    "trace": [\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:341",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:305",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:390",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:497",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:516",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:206",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:71",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:483",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:259",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:159",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php:19",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:160",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php:52",\n'
                                                      '        '
                                                      '"/Users/xxx/code/xxx/api/vendor/laravel/framework…'}],
                           'id': 1,
                           'mrkdwn_in': ['fields'],
                           'text': 'Expected response code 354 but got code '
                                   '"550", with message "550 5.7.0 Requested '
                                   'action not taken: too many emails per '
                                   'second\n'
                                   '"',
                           'title': 'Message',
                           'ts': 1584604142}],
    'bot_id': 'xxx',
    'subtype': 'bot_message',
    'text': '',
    'ts': '1584604144.001900',
    'type': 'message'}`

**Comment by sgratzl** [comment]
I assume it has something to do with the attachments

**Comment by sgratzl** [comment]
can you try to use the `as_user` flag:

```

**Comment by mqdeandrade** [comment]
@sgratzl running with that flag fixed it. Thanks so much! Do you know the underlying cause?

**Comment by lucbas** [comment]
Can confirm is that using the --as_user flag is working. My command looks like this:

`slacker-cleaner --token xxxx --message --group groupName --bot --as_user --perform --rate 1`

**Comment by sgratzl** [comment]
great. As far as I understood depending on the flag is using a different permission scope. It might has something to do with the recent scope simplifications (see also https://github.com/sgratzl/slack-cleaner/pull/69). But I have no idea why they are triggering an invalid_argument exception.

**Comment by narongwate-scm** [comment]
> can you try to use the `as_user` flag:
> 
> ```
> --as_user            Pass true to delete the message as the authed user. Bot
>                        users in this context are considered authed users.
> ```

That it works. thanks, @sgratzl to help me

**Comment by carlopug** [comment]
Hello,
if I try with:

`slack-cleaner --token TOKEN -message --channel CHANNELNAME --bot  --before 20190808 --perform --rate 1` 

I got the error: `Failed to delete (invalid_arguments)->`

if I add `--as_user`... 
I got the error: `Failed to delete (cant_delete_message)->`.

What can I try?

**Comment by carlopug** [comment]
> Hello,
> if I try with:
> 
> `slack-cleaner --token TOKEN -message --channel CHANNELNAME --bot --before 20190808 --perform --rate 1`
> 
> I got the error: `Failed to delete (invalid_arguments)->`
> 
> if I add `--as_user`...
> I got the error: `Failed to delete (cant_delete_message)->`.
> 
> What can I try?

Sorry! Done using User Token Scopes in place of Bot Token Scopes with OAuth Access Token.

**Comment by Deleetdk** [comment]
`--as_user` also works for me. Can we add that to the `README.md`?? It breaks once in a while because of threads but that's another bug I think.

**Comment by sgratzl** [comment]
I created and pinned https://github.com/sgratzl/slack-cleaner/issues/73 which gives exactly this hint.

**Comment by stevetso** [comment]
Can you confirm your token is started with **"xoxp"**?
