### ISSUE TITLE
Replies are not cleaned

### ISSUE THREAD

**Issue by philiiiiiipp** [sgratzl/slack-cleaner#74]
**Describe the bug**

I have been trying to completely clean out a slack channel with:
```bash
docker run -it --rm sgratzl/slack-cleaner -c "slack-cleaner --token $SLACK_TOKEN --message --channel $CHANNEL --user \"*\" --bot --as_user --perform" 
```

But it seems to keep the replies. If I am running the same command again, I get 
```
Failed to delete (message_not_found)->
{   u'hidden': True,
    u'last_read': u'1587533958.000300',
    u'latest_reply': u'1587533958.000300',
    u'reply_count': 32,
    u'reply_users': [u'UUFELML9X', u'U75TBYH9N'],
    u'reply_users_count': 2,
    u'subscribed': True,
    u'subtype': u'tombstone',
    u'text': u'This message was deleted.',
    u'thread_ts': u'1587490251.011600',
    u'ts': u'1587490251.011600',
    u'type': u'message',
    u'user': u'USLACKBOT'}
Failed to delete (message_not_found)->
{   u'hidden': True,
    u'last_read': u'1587472946.007400',
    u'latest_reply': u'1587472946.007400',
    u'reply_count': 1,
    u'reply_users': [u'UUFELML9X'],
    u'reply_users_count': 1,
    u'subscribed': True,
    u'subtype': u'tombstone',
    u'text': u'This message was deleted.',
    u'thread_ts': u'1587472719.006800',
    u'ts': u'1587472719.006800',
    u'type': u'message',
    u'user': u'USLACKBOT'}
Failed to delete (message_not_found)->
{   u'hidden': True,
    u'latest_reply': u'1587105514.000400',
    u'reply_count': 2,
    u'reply_users': [u'UUFELML9X'],
    u'reply_users_count': 1,
    u'subscribed': False,
    u'subtype': u'tombstone',
    u'text': u'This message was deleted.',
    u'thread_ts': u'1587100977.000100',
    u'ts': u'1587100977.000100',
    u'type': u'message',
    u'user': u'USLACKBOT'}
```

**To Reproduce**
In my case it was just a channel full of messages by a bot or user followed by replies of users. 

**Expected behavior**
It should clean out all messages

**Screenshots**
<img width="802" alt="Screenshot 2020-04-29 at 08 56 17" src="https://user-images.githubusercontent.com/1035746/80568536-7caf1d80-89f7-11ea-9948-f4ede144c9d8.png">

**Comment by sgratzl** [comment]
hm...

https://github.com/sgratzl/slack-cleaner/blob/85f62d9789e88c6b77cbb1ebc75ec20f81d4a2e7/slack_cleaner/cli.py#L170-L176

is the relevant code for deleting replies, so interesting what is going on. I try to reproduce it.

In the meanwhile you could try using https://github.com/sgratzl/slack_cleaner2 which is a python module allowing more control about messages and replies. 

code wise it would be something like (untested)

```py
from slack_cleaner2 import SlackCleaner

s = SlackCleaner('SECRET TOKEN')
channel = s.c.CHANNEL_NAME
for msg in channel.msgs():
  for reply in msg.replies():
    reply.delete()
  msg.delete()
```

**Comment by philiiiiiipp** [comment]
Yes, I also felt it was weird because I saw https://github.com/sgratzl/slack-cleaner/pull/55 

I will have a look at the slack cleaner 2.

**Comment by sgratzl** [comment]
seems to be a general bug, see https://github.com/sgratzl/slack_cleaner2/issues/17

**Comment by philiiiiiipp** [comment]
Ah ok, are you planning on including it in this package as well ?

**Comment by joshua1** [comment]
@sgratzl  any chance you will apply the same fix here? since a number of us may not be using or coding in python

**Comment by sgratzl** [comment]
see v0.7.1
