### ISSUE TITLE
No longer deletes threaded messages

### ISSUE THREAD

**Issue by chrisalbon** [sgratzl/slack-cleaner#76]
Around late March, `slack-cleaner` stopped being able to delete threaded messages. The top message of a thread is deleted, however the replies are not.

**Comment by sgratzl** [comment]
have you tried https://github.com/sgratzl/slack-cleaner/releases/tag/v0.7.1

**Comment by chrisalbon** [comment]
Yep that fixed it. User error on my part. Closing issue with my thanks.

**Comment by sgratzl** [comment]
for the records: 

> Effective March 31, 2020
> Parent messages in a thread will no longer explicitly list their replies. Instead of a large replies array containing threaded message replies, we'll provide a lighter-weight list of reply_users, plus a reply_users_count and the latest_reply message. These new fields are already available. We'll remove the replies array on October 18, 2019 March 31st, 2020. Read up on threaded messages here.
