### ISSUE TITLE
No longer possible to create legacy tokens

### ISSUE THREAD

**Issue by titaniumbones** [sgratzl/slack-cleaner#78]
as of yesterday, it's no longer possible to create legacy tokens: https://api.slack.com/changelog/2020-02-legacy-test-token-creation-to-retire#prepare 

I think that the main thing to be done is to update permissions required, but I'm not sure how that is done.

THanks so much ofr htis tool and Ireally hope it's possible to continue using it.

**Comment by sgratzl** [comment]
creating a custom Slack app by following https://github.com/sgratzl/slack-cleaner#configuring-app should work without problems (except #77 of which a bugfix is on the way)
