### ISSUE TITLE
conversations.list limit 100 default issue

### ISSUE THREAD

**Issue by singleuseonly** [sgratzl/slack-cleaner#84]
It appears the conversations.list api is called without the *limit* argument and the channel lists are truncated. 

eg.

slack-cleaner --token <token> --info

returns users, public, private channel lists, all truncated to 100 in length. 

I have lots missing!

any channels not included in the first 100 cannot be cleaned by reference using the --channel or --direct arguments

---------------------------------------------------
Running slack-cleaner v0.7.3
Channel, direct message or private group not found

**Comment by sgratzl** [comment]
thx good catch. 

atm. I quick fix it by setting the limit to 1000 and released 0.7.4

**Comment by singleuseonly** [comment]
thanks samuel - i patched slacker with the 1000 limit as a work around :)

appreciate your work. thank you
