### ISSUE TITLE
Can't see privat channels

### ISSUE THREAD

**Issue by nessor** [sgratzl/slack-cleaner#87]
Hey guys
i have a problem that i do not see any private channels. When executing the command 

```
slack-cleaner --token <my_token> --info
```

everything is listed, except the private channels. These are simply empty.
As stated in the readme, I have set the following permissions:

- groups:history
- groups:read
- chat:write
- users:read

The execution of the command 

```
/slack-cleaner --token <TOKEN> --message --channel private_channel --user "*"
```

as well as

```
./slack-cleaner --token <TOKEN> --message --group private_channel --user "*"
```

returns with:
```
Running slack-cleaner v0.7.4
channel, direct message or private group not found
```

Am I doing something wrong?

**Comment by sgratzl** [comment]
are you using a bot or user token? as far as I know bots can only see the private channels they joined

**Comment by stevetso** [comment]
Try these parameters:

Public channel: --channel

Private channel: --group

**Comment by nessor** [comment]
@sgratzl This solved my problem :) Thanks!
