### ISSUE TITLE
Docker image returning error

### ISSUE THREAD

**Issue by azfarhashmi** [sgratzl/slack-cleaner#88]
I tried provided docker image but it is returning error on execution.

`import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
/usr/local/bin/slack-cleaner: line 7: from: command not found
/usr/local/bin/slack-cleaner: slack-cleaner: line 10: syntax error near unexpected token `('
/usr/local/bin/slack-cleaner: slack-cleaner: line 10: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
`

**Comment by sgratzl** [comment]
should be fixed with https://github.com/sgratzl/slack-cleaner/commit/8eb2db260b40b89a2ca2fd461c3ee2c1ac3eed4a. Please pull the image in a few minutes and try again.
