### ISSUE TITLE
slacker.Error: invalid_auth

### ISSUE THREAD

**Issue by cheesimp** [sgratzl/slack-cleaner#93]
Hey guys,

I want to delete all messages from the #general channel.

I am the owner of my slack workspace.
I installed the slack cleaner using `pip install slack-cleaner`.
I created an app with bot scopes `channels:history`, `channels:read`, chat:write` and `users:read`.
I copied the bot user oauth token and using it it `slack-cleaner --token <TOKEN> --message --channel general --user "*"`.

But getting error
```
Running slack-cleaner v0.7.4
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 5, in <module>
    from slack_cleaner.cli import main
  File "/usr/local/lib/python2.7/site-packages/slack_cleaner/cli.py", line 84, in <module>
    init_user_dict()
  File "/usr/local/lib/python2.7/site-packages/slack_cleaner/cli.py", line 66, in init_user_dict
    res = slack.users.list().body
  File "/usr/local/lib/python2.7/site-packages/slacker/__init__.py", line 331, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/usr/local/lib/python2.7/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/usr/local/lib/python2.7/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: invalid_auth
```

**Expected behavior**
It should work as expected.

**Context**

- Version: `Version 0.7.4`
- Python Version: `Python 2.7.17`

**Comment by leom806** [comment]
Hey guys

Same here running with `docker run`:

```
  File "/usr/local/bin/slack-cleaner", line 5, in <module>
    from slack_cleaner.cli import main
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner/cli.py", line 84, in <module>
    init_user_dict()
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner/cli.py", line 66, in init_user_dict
    res = slack.users.list().body
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 331, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: invalid_auth
```

**Comment by spheron1** [comment]
I had the exact same invalid_auth problem (even when granting all bot and user OAuth permissios to the app at Slack out of desperation) and ended up using https://github.com/sgratzl/slack_cleaner2 to overcome it.
I guess there must have been some kind of API change.

**Comment by hangingman** [comment]
I had the same problem.
But, it seems slack-cleaner2 is working
https://github.com/sgratzl/slack_cleaner2

- My commands
```shell
$ python --version
Python 3.6.10

$ python
Python 3.6.10 (default, Aug 22 2020, 00:49:22) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from slack_cleaner2 import *
>>> 
>>> s = SlackCleaner('xoxp-***')
>>> 
>>> s.users
this will list all users in workspace
[xxx, xxx...]

>>> [msg for msg in s.c['YOUR CHANNEL NAME'].msgs(with_replies=True)]
this will list all message in a channel
```

**Comment by tofr** [comment]
thanks all.  Been getting the same error repeatedly. Will just give 2 a go...

**Comment by rinopo** [comment]
The problem seems to be with the upstream [Slacker](https://github.com/os/slacker) module, which has been discontinued.
Authorization token has to be sent inside HTTP headers or inside the POST body, not inside the GET query params as Slacker does.
https://api.slack.com/web#slack-web-api__authentication

**Comment by rinopo** [comment]
Patching `/usr/local/lib/python3.7/site-packages/slacker/__init__.py` with changes from the following fork has saved my day, at least for my temporary use case:
https://github.com/ismith/slacker/commit/8ff928c59ec77b047b7270d96936e3df7e2bc4fb

**Comment by lyaschuchenko** [comment]
slack deprecated legacy token.

**Comment by sgratzl** [comment]
please migrate to https://github.com/sgratzl/slack_cleaner2 since I don't have the capacity to fix the underlying/dependent slacker library
